### ISSUE TITLE
Bug: Public page search result pagination broken

### ISSUE THREAD

**Issue by jrbgit** [ArchiveBox/ArchiveBox#1065] opened 2022-12-21 05:14 UTC
#### Describe the bug

Pagination on the public page search results does not pass the query along to the next page. As a result the search results are not longer displayed and instead all items are.

#### Steps to reproduce

Perform a search on the public page that has at least 2 pages of results. Try navigating to next/last/etc.

#### ArchiveBox version

```logs
replace this line with the *full*, unshortened output of running `archivebox version`
```

john@debian-s-4vcpu-8gb-intel-nyc1-01:/mnt/volume_nyc1_01/ab$ archivebox --version
ArchiveBox v0.6.2
Cpython Linux Linux-5.10.0-20-amd64-x86_64-with-glibc2.31 x86_64
IN_DOCKER=False DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND_ENGINE=ripgrep

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.6.2          valid     /usr/local/bin/archivebox
 √  PYTHON_BINARY         v3.9.2          valid     /usr/bin/python3.9
 √  DJANGO_BINARY         v3.1.14         valid     /usr/local/lib/python3.9/dist-packages/django/bin/django-admin.py
 √  CURL_BINARY           v7.74.0         valid     /usr/bin/curl
 √  WGET_BINARY           v1.21           valid     /usr/bin/wget
 √  NODE_BINARY           v18.12.1        valid     /home/john/.nvm/versions/node/v18.12.1/bin/node
 √  SINGLEFILE_BINARY     v1.0.23         valid     ./node_modules/single-file/cli/single-file
 √  READABILITY_BINARY    v0.0.4          valid     ./node_modules/readability-extractor/readability-extractor
 √  MERCURY_BINARY        v1.0.0          valid     ./node_modules/@postlight/mercury-parser/cli.js
 √  GIT_BINARY            v2.30.2         valid     /usr/bin/git
 √  YOUTUBEDL_BINARY      v2021.12.17     valid     /usr/local/bin/youtube-dl
 √  CHROME_BINARY         v108.0.5359.124  valid     /usr/bin/chromium
 √  RIPGREP_BINARY        v12.1.1         valid     /usr/bin/rg

[i] Source-code locations:
 √  PACKAGE_DIR           23 files        valid     /usr/local/lib/python3.9/dist-packages/archivebox
 √  TEMPLATES_DIR         3 files         valid     /usr/local/lib/python3.9/dist-packages/archivebox/templates
 √  CUSTOM_TEMPLATES_DIR  3 files         valid     /mnt/volume_nyc1_01/ArchiveBox/archivebox/templates

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled
 -  COOKIES_FILE          -               disabled

[i] Data locations:
 √  OUTPUT_DIR            6 files         valid     /mnt/volume_nyc1_01/ab
 √  SOURCES_DIR           15 files        valid     ./sources
 √  LOGS_DIR              2 files         valid     ./logs
 √  ARCHIVE_DIR           327 files       valid     ./archive
 √  CONFIG_FILE           353.0 Bytes     valid     ./ArchiveBox.conf
 √  SQL_INDEX             3.1 MB          valid     ./index.sqlite3

**Comment by pirate** [comment] 2022-12-21 06:14
Duplicate of: https://github.com/ArchiveBox/ArchiveBox/issues/995

**Closed by pirate** 2022-12-21 06:14 UTC
