### ISSUE TITLE
Bulk snapshots action from list page do not work, result = "⚠️No action selected."

### ISSUE THREAD

**Issue by rmohns** [ArchiveBox/ArchiveBox#1184] opened 2023-07-15 15:11 UTC
### Discussed in https://github.com/ArchiveBox/ArchiveBox/discussions/1183

<div type='discussions-op-text'>

<sup>Originally posted by **rmohns** July 15, 2023</sup>
Hoping someone has seen this. If I select one or more snapshots from the list page, whilst logged in, none of the action buttons (pull, re-snapshot, reset, delete) seem to work. After selecting one, the page reloads and says "⚠️No action selected."
![Screenshot 2023-07-15 at 10 59 50 AM](https://github.com/ArchiveBox/ArchiveBox/assets/2131133/1ec30ba9-8b32-4634-b25b-f357c4a215be)
![Screenshot 2023-07-15 at 11 00 08 AM](https://github.com/ArchiveBox/ArchiveBox/assets/2131133/59620d65-ec66-48fe-b8e9-1d1b2880ac74)

version info:

```
@Synner:/volume1/docker/projects/archivebox$ docker-compose run -T --rm archivebox version
ArchiveBox v0.6.2
Cpython Linux Linux-4.4.302+-x86_64-with-glibc2.28 x86_64
IN_DOCKER=True DEBUG=False IS_TTY=False TZ=UTC SEARCH_BACKEND_ENGINE=ripgrep

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.6.2          valid     /usr/local/bin/archivebox                                                   
 √  PYTHON_BINARY         v3.9.5          valid     /usr/local/bin/python3.9                                                    
 √  DJANGO_BINARY         v3.1.10         valid     /usr/local/lib/python3.9/site-packages/django/bin/django-admin.py           
 √  CURL_BINARY           v7.64.0         valid     /usr/bin/curl                                                               
 √  WGET_BINARY           v1.20.1         valid     /usr/bin/wget                                                               
 √  NODE_BINARY           v15.14.0        valid     /usr/bin/node                                                               
 √  SINGLEFILE_BINARY     v0.3.16         valid     /node/node_modules/single-file/cli/single-file                              
 -  READABILITY_BINARY    -               disabled  /node/node_modules/readability-extractor/readability-extractor              
 √  MERCURY_BINARY        v1.0.0          valid     /node/node_modules/@postlight/mercury-parser/cli.js                         
 -  GIT_BINARY            -               disabled  /usr/bin/git                                                                
 √  YOUTUBEDL_BINARY      v2021.04.26     valid     /usr/local/bin/youtube-dl                                                   
 √  CHROME_BINARY         v90.0.4430.93   valid     /usr/bin/chromium                                                           
 √  RIPGREP_BINARY        v0.10.0         valid     /usr/bin/rg                                                                 

[i] Source-code locations:
 √  PACKAGE_DIR           22 files        valid     /app/archivebox                                                             
 √  TEMPLATES_DIR         3 files         valid     /app/archivebox/templates                                                   
 -  CUSTOM_TEMPLATES_DIR  -               disabled                                                                              

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled                                                                              
 -  COOKIES_FILE          -               disabled                                                                              

[i] Data locations:
 √  OUTPUT_DIR            5 files         valid     /data                                                                       
 √  SOURCES_DIR           7 files         valid     ./sources                                                                   
 √  LOGS_DIR              1 files         valid     ./logs                                                                      
 √  ARCHIVE_DIR           15 files        valid     ./archive                                                                   
 √  CONFIG_FILE           81.0 Bytes      valid     ./ArchiveBox.conf                                                           
 √  SQL_INDEX             268.0 KB        valid     ./index.sqlite3                                                             
```
</div>

**Comment by pirate** [comment] 2023-08-13 23:44
Closing as duplicate of https://github.com/ArchiveBox/ArchiveBox/issues/875 since they're the same underlying issue with Safari, follow that issue for progress updates / further discussion.

**Closed by pirate** 2023-08-13 23:44 UTC
