### ISSUE TITLE
Dockerfile changes

### ISSUE THREAD

**Issue by shepner** [ArchiveBox/ArchiveBox#556] opened 2020-11-29 23:21 UTC
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves

Minor stuff to make the Dockerfile a bit more friendly to work with

## What hacks or alternative solutions have you tried to solve the problem?

This are some initial things Ive run across:
* After installing the software, run `USER $ARCHIVEBOX_USER` to switch from root
* Provide ENV vars so the `useradd` and `useradd` commands support user definable UID and GID.
* I dont seem to be able to get the TZ to change out of the default UTC setting.
* Ive had to do a fair amount of external scripting, tinkering, etc related to this container so I can reliably get it working in my environment
  * Perhaps add a script to detect that the config dir is missing and automatically run `archivebox init`?
  * The `archivebox manage createsuperuser` is the only reliable way Ive been able to setup a working account.  (this is related to my comment in [#554](https://github.com/ArchiveBox/ArchiveBox/issues/554))
  * Running `archivebox init` is a dangerous task (data is lost when the DB is recreated) but Ive needed to run it a couple times now.  My [startup script](https://github.com/shepner/asyla/blob/master/docker/archivebox.sh) now has a special setting for it.   Perhaps add a YAML metadata file into the root of each snapshot folder?  This would permit the sqlite DB to be used exclusively as a data cache rather then the system of record.

FWIW, I rather like how [linuxserver.io](https://www.linuxserver.io) has polished/refined their base image and so I tend to template my own configs upon their work.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [ ] I'm willing to contribute dev time / money to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by cdvv7788** [comment] 2020-11-29 23:58
`archivebox init` should not be dangerous. Did some folders get wiped, or some entries in the database get lost when you ran it? Can you reliable reproduce it? It would be very helpful if that is the case.

**Comment by shepner** [comment] 2020-11-30 14:56
I debated about mentioning this in here so have opened [#557](https://github.com/ArchiveBox/ArchiveBox/issues/557) to avoid loosing the point of this enhancement ticket

**Comment by pirate** [comment] 2021-02-01 10:29
progress update:

- [x] After installing the software, run USER $ARCHIVEBOX_USER to switch from root (done via the entrypoint script)
- [x] Provide ENV vars so the useradd and useradd commands support user definable UID and GID. (now respects PUID and GUID env vars in `>=v0.5.4`)
- [ ] I dont seem to be able to get the TZ to change out of the default UTC setting.

**Comment by pirate** [comment] 2021-04-06 06:25
Going to close this for now since most of the suggestions have been implemented. We'll track timezone support in a separate issue.

**Closed by pirate** 2021-04-06 06:25 UTC
Labels: difficulty: easy, status: wip, touches: config
