### ISSUE TITLE
Bug: Long link results in OSError: File name too long

### ISSUE THREAD

**Issue by 235** [ArchiveBox/ArchiveBox#1310] opened 2024-01-04 18:00 UTC
Added a rather long link from a collection. After it was indexed, UI started crashing intermittently with HTTP error 500, suggesting that the link resulted in rather long folder name, crashing the library.

#### Describe the bug
Link added: `https://curious.bio/Akademie,Aquaponik,BioFablab,Biokunstoffe,Biologie,Bio%C3%B6konomie,Biotechnology,Commons,DataScience,Design,DIY,DIYBIO,Experimentierfeld,FabCity,FabLab,Gemeinwohl,Hamburg,Kreislaufwirtschaft,Kunst,Makerspace,MINT,Oberhafen,Oberhafenquartier,Open-Data,Open-Hardware,Open-Source,OpenBiolab,Permakultur,Pilzwerkstatt,Reallabor,Sch%C3%BClerlabor,Smart-City,TechLab,Umwelt,Weiterbildung/plankton/`

#### Steps to reproduce

1. Add a very long link
2. Wait it to be indexed, resulting in a long path 
3. Refresh UI to view the result, observe HTTP error 500

#### Screenshots or log output

```
"GET / HTTP/1.1" 302 0
"GET /admin/core/snapshot/ HTTP/1.1" 200 107511
"GET /admin/jsi18n/ HTTP/1.1" 200 3191
Internal Server Error: /admin/core/snapshot/
Traceback (most recent call last):
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/db/models/options.py", line 575, in get_field
    return self.fields_map[field_name]
KeyError: 'title_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 265, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 296, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/db/models/options.py", line 577, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Snapshot has no field named 'title_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 341, in result_list
    'results': list(results(cl)),
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 317, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 308, in __init__
    super().__init__(*items)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 233, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 274, in lookup_field
    value = attr(obj)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/archivebox/core/admin.py", line 164, in title_str
    canon = obj.as_link().canonical_outputs()
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/archivebox/index/schema.py", line 427, in canonical_outputs
    'wget_path': wget_output_path(self),
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/archivebox/util.py", line 116, in typechecked_function
    return func(*args, **kwargs)
  File "/home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/archivebox/extractors/wget.py", line 170, in wget_output_path
    if search_dir.exists():
  File "/usr/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
OSError: [Errno 36] File name too long: '/home/opr/soft/archivebox/data/archive/1704377003.792509/curious.bio/Akademie,Aquaponik,BioFablab,Biokunstoffe,Biologie,Bioökonomie,Biotechnology,Commons,DataScience,Design,DIY,DIYBIO,Experimentierfeld,FabCity,FabLab,Gemeinwohl,Hamburg,Kreislaufwirtschaft,Kunst,Makerspace,MINT,Oberhafen,Oberhafenquartier,Open-Data,Open-Hardware,Open-Source,OpenBiolab,Permakultur,Pilzwerkstatt,Reallabor,Schülerlabor,Smart-City,TechLab,Umwelt,Weiterbildung/plankton'
"GET /admin/core/snapshot/?p=1 HTTP/1.1" 500 145
```

#### ArchiveBox version

```
ArchiveBox v0.7.1 Cpython Linux Linux-6.1.0-1027-oem-x86_64-with-glibc2.35 x86_64
DEBUG=False IN_DOCKER=False IN_QEMU=False IS_TTY=True TZ=UTC FS_ATOMIC=True FS_REMOTE=False FS_USER=1000:1000 FS_PERMS=644 SEARCH_BACKEND=ripgrep

[i] Dependency versions:
 √  PYTHON_BINARY         v3.10.12        valid     /usr/bin/python3.10                                                         
 √  SQLITE_BINARY         v2.6.0          valid     /usr/lib/python3.10/sqlite3/dbapi2.py                                       
 √  DJANGO_BINARY         v3.1.14         valid     /home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/django/__init__.py
 √  ARCHIVEBOX_BINARY     v0.7.1          valid     /home/opr/soft/archivebox/ab_venv/bin/archivebox                            

 √  CURL_BINARY           v7.81.0         valid     /usr/bin/curl                                                               
 √  WGET_BINARY           v1.21.2         valid     /usr/bin/wget                                                               
 √  NODE_BINARY           v20.9.0         valid     /usr/local/bin/node                                                         
 √  SINGLEFILE_BINARY     v1.1.46         valid     ./node_modules/single-file-cli/single-file                                  
 √  READABILITY_BINARY    v0.0.11         valid     ./node_modules/readability-extractor/readability-extractor                  
 √  MERCURY_BINARY        v1.0.0          valid     ./node_modules/@postlight/parser/cli.js                                     
 √  GIT_BINARY            v2.34.1         valid     /usr/bin/git                                                                
 √  YOUTUBEDL_BINARY      v2023.12.30     valid     /home/opr/soft/archivebox/ab_venv/bin/yt-dlp                                
 √  CHROME_BINARY         v120.0.6099.199  valid     /usr/bin/google-chrome                                                      
 √  RIPGREP_BINARY        v13.0.0         valid     /usr/bin/rg                                                                 

[i] Source-code locations:
 √  PACKAGE_DIR           24 files        valid     /home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/archivebox   
 √  TEMPLATES_DIR         4 files         valid     /home/opr/soft/archivebox/ab_venv/lib/python3.10/site-packages/archivebox/templates
 -  CUSTOM_TEMPLATES_DIR  -               disabled  None                                                                        

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled  None                                                                        
 -  COOKIES_FILE          -               disabled  None                                                                        

[i] Data locations:
 √  OUTPUT_DIR            7 files         valid     /home/opr/soft/archivebox/data                                              
 √  SOURCES_DIR           52 files        valid     ./sources                                                                   
 √  LOGS_DIR              1 files         valid     ./logs                                                                      
 √  ARCHIVE_DIR           474 files       valid     ./archive                                                                   
 √  CONFIG_FILE           259.0 Bytes     valid     ./ArchiveBox.conf                                                           
 √  SQL_INDEX             4.6 MB          valid     ./index.sqlite3                                                             
```

**Comment by pirate** [comment] 2024-01-04 19:29
Closing as duplicate of https://github.com/ArchiveBox/ArchiveBox/issues/1107

It only affects the wget extractor, other extractors should continue to work ok.

**Closed by pirate** 2024-01-04 19:29 UTC
