### ISSUE TITLE
Feature Request: Whole-site archiving with link-rewriting to point to archived versions

### ISSUE THREAD

**Issue by charlesangus** [ArchiveBox/ArchiveBox#893] opened 2021-11-21 16:28 UTC
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves

- Archive an entire site, rewrite URLs to point to archives, so the archive is entirely self-contained. Like how archive.org does it - if I'm viewing an archived web page, the links I click point to other archived pages, not to the live versions on the web.
- Organize snapshots imported this way hierarchically under the top-level domain, so essentially I can go to the top-level archived page, and then naturally navigate through the site, hitting only archived pages

If I'm archiving a site with say, thousands of pages. each snapshot is an island unto itself, which basically breaks any kind of flow of revisiting the archived pages. To follow a link, I have to hover, see where the link is going, and then go back to the snapshots page, search for that link, and then click on the snapshot. Quite cumbersome.

### Example

e.g. start page:

https://mygreatblog.com/

found links:

https://mygreatblog.com/2019/01/mygreatarticle.html
https://mygreatblog.com/2021/01/mygreatarticle-part-ii.html

Archivebox archives both pages and rewrites links so that internal links still work and point to local copies:

https://mygreatblog.com/ --> https://myarchiveboxinstance.com/archive/<archive id>/index.html
https://mygreatblog.com/2019/01/mygreatarticle.html --> https://myarchiveboxinstance.com/archive/<archive id>index.html

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Point to top-level page, say "archive whole site", and get an archive of the whole site, with all links pointing to the archived versions of the links.

## What hacks or alternative solutions have you tried to solve the problem?

Currently using an external crawler to find all the pages on the site and adding them to ArchiveBox en masse, but this just gets me thousands of snapshots with no way to navigate between them.

## How badly do you want this new feature?

 - [x] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [ ] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment] 2021-11-23 03:13
Duplicate of #191. 😉

**Closed by pirate** 2021-11-23 03:13 UTC
Labels: status: idea phase

**Comment by charlesangus** [comment] 2021-11-23 06:30
Well, half a dupe, I'll admit.

Using an external crawler doesn't really work properly, because each archived page is a standalone thing.

In order to be able to browse the archives conveniently, archived should rewrite urls to point to the archive box version.

If that was implemented, using an external crawler would basically work fine.

As it is, it works for incidental archiving of a page here and there, but trying to archive anything systematically gets impossible to browse.

**Comment by pirate** [comment] 2021-11-26 01:27
URL rewriting is definitely a subset of the other issue, it wouldn't make sense to provide recursive whole-site archiving without it.

**Comment by pirate** [comment] 2024-04-11 08:03
More detailed comment about URL rewriting for anyone landing here via Google: https://github.com/ArchiveBox/ArchiveBox/discussions/1395#discussioncomment-9063232
