### ISSUE TITLE
Question: privacy pop up

### ISSUE THREAD

**Issue by Wanty5883** [ArchiveBox/ArchiveBox#723] opened 2021-04-26 05:31 UTC
Do you have a way to remove the privacy pop up ?
Can it is be done automatically. Having to do this manually sounds like too much time required.
Probably a redundant question, but I haven't been able to find what I am looking for.

Thanks !

**Comment by pirate** [comment] 2021-04-26 17:55
Closing as duplicate of: https://github.com/ArchiveBox/ArchiveBox/issues/175 please follow that issue for updates.

**Closed by pirate** 2021-04-26 17:55 UTC
