### ISSUE TITLE
Feature Request: Use of tools like gallery-dl to archive specific websites.

### ISSUE THREAD

**Issue by TheAnachronism** [ArchiveBox/ArchiveBox#767] opened 2021-06-10 22:31 UTC
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves
Archiving stuff from sites like DeviantArt is very difficult if not impossible because of how those sites kind of prevent such crawling or downloading the content by a simple wget.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
Tools like gallery-dl solve this issue because they're made to download and archive content from those sites.

## What hacks or alternative solutions have you tried to solve the problem?
The only thing that would come to mind is to download the site manually and then somehow upload it to ArchiveBox. But because WARC upload isn't supported yet this gets difficult

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment] 2021-06-11 00:59
Duplicate of: https://github.com/ArchiveBox/ArchiveBox/issues/564

**Closed by pirate** 2021-06-11 00:59 UTC
Labels: status: idea phase
