### ISSUE TITLE
Bug: Leaking Chrome processes

### ISSUE THREAD

**Issue by WesleyAC** [ArchiveBox/ArchiveBox#858] opened 2021-09-27 01:48 UTC
#### Describe the bug

ArchiveBox leaks chrome/chromium processes during use. I'm not sure the exact things that triggered this, but archiving ~170 pages seemed to leak ~50 chrome processes. Sorry that this isn't more useful, I didn't notice the processes until a few hours after I was done using ArchiveBox.

#### Steps to reproduce

I'm unsure the exact steps to trigger — mostly `archivebox add` commands.

#### Screenshots or log output

N/A

#### ArchiveBox version

```logs
ArchiveBox v0.6.2
Cpython Linux Linux-5.10.66-x86_64-with-glibc2.33 x86_64
IN_DOCKER=False DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND_ENGINE=ripgrep

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.6.2          valid     /nix/store/xfqwr74qli0fm186dj5006960mn5pw38-archivebox-0.6.2/bin/archivebox 
 √  PYTHON_BINARY         v3.9.6          valid     /nix/store/i1m8r7mv8h47wr850cdsxksy22lv6gsz-python3-3.9.6/bin/python3.9     
 √  DJANGO_BINARY         v3.1.7          valid     /nix/store/889dn8m5c562vy949frmxdna4kxfm8rf-python3.9-Django-3.1.7/lib/python3.9/site-packages/django/bin/django-admin.py
 √  CURL_BINARY           v7.76.1         valid     /nix/store/blaac45yvgljsy15jdxgvxxqs6w5yhqj-curl-7.76.1-bin/bin/curl        
 -  WGET_BINARY           -               disabled  /run/current-system/sw/bin/wget                                             
 √  NODE_BINARY           v14.17.6        valid     /nix/store/zqgmd79n5p0mdaw4sbvkv7gvrmks76a2-nodejs-14.17.6/bin/node         
 √  SINGLEFILE_BINARY     v0.3.31         valid     ./node_modules/single-file/cli/single-file                                  
 √  READABILITY_BINARY    v0.0.3          valid     ./node_modules/readability-extractor/readability-extractor                  
 √  MERCURY_BINARY        v1.0.0          valid     ./node_modules/@postlight/mercury-parser/cli.js                             
 -  GIT_BINARY            -               disabled  /run/current-system/sw/bin/git                                              
 -  YOUTUBEDL_BINARY      -               disabled  /nix/store/vmfzdc3wrnhhklk8fm5zrz342vp9kwd4-python3.9-youtube-dl-2021.06.06/bin/youtube-dl
 √  CHROME_BINARY         v93.0.4577.82   valid     /run/current-system/sw/bin/chromium-browser                                 
 √  RIPGREP_BINARY        v12.1.1         valid     /run/current-system/sw/bin/rg                                               

[i] Source-code locations:
 √  PACKAGE_DIR           23 files        valid     /nix/store/xfqwr74qli0fm186dj5006960mn5pw38-archivebox-0.6.2/lib/python3.9/site-packages/archivebox
 √  TEMPLATES_DIR         3 files         valid     /nix/store/xfqwr74qli0fm186dj5006960mn5pw38-archivebox-0.6.2/lib/python3.9/site-packages/archivebox/templates
 -  CUSTOM_TEMPLATES_DIR  -               disabled                                                                              

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled                                                                              
 -  COOKIES_FILE          -               disabled                                                                              

[i] Data locations:
 √  OUTPUT_DIR            6 files         valid     /home/wesleyac/code/notebook/data/archivebox                                
 √  SOURCES_DIR           204 files       valid     ./sources                                                                   
 √  LOGS_DIR              1 files         valid     ./logs                                                                      
 √  ARCHIVE_DIR           157 files       valid     ./archive                                                                   
 √  CONFIG_FILE           246.0 Bytes     valid     ./ArchiveBox.conf                                                           
 √  SQL_INDEX             1.4 MB          valid     ./index.sqlite3                                                             
```

**Comment by pirate** [comment] 2021-09-27 20:02
Duplicate of #746

**Closed by pirate** 2021-09-27 20:02 UTC
