### ISSUE TITLE
Bugfix: deleted item re-appears upon next import of URLs

### ISSUE THREAD

**Issue by mauvity** [ArchiveBox/ArchiveBox#433] opened 2020-08-10 07:13 UTC
Thank you in advance for your help,
Sorry if this isn't experienced universally and it's just something I'm not doing right 😕

#### Describe the bug

Deleted item is re-imported upon the next import of (unrelated) URLs

#### Steps to reproduce

1. Delete item from web UI by clicking on item timestamp > Delete
2. Import new (unrelated) URLs in web UI
3. New URLs import correctly, but the recently deleted item is also re-imported

#### Software versions
 - OS: Debian 10
 - ArchiveBox version: Docker c8e3aed

**Comment by cdvv7788** [comment] 2020-08-10 14:19
I was able to reproduce the bug. @mauvity for now, as a workaround, you can select the items you want to delete from the list and click the `delete` button at the top right: 
![image](https://user-images.githubusercontent.com/5531776/89792666-7fd3a280-daea-11ea-88e0-d1d31a0eddcc.png)

I will send a PR to fix the issue soon.

**Comment by pirate** [comment] 2020-08-10 14:29
@cdvv7788 the timestamp > delete version will be fixed automatically once we remove the json main index

don't bother fixing it for now, it would just add a bunch of workaround complexity for a problem that's going away soon anyway.

**Comment by cdvv7788** [comment] 2020-08-10 14:31
Hmmm, true...the index issue will go away. I will hide the `delete` button from the detail template for now then, to avoid confusion.

**Comment by cdvv7788** [comment] 2020-08-10 14:35
Ok. Please leave this open so we don't forget to check back once we merge the index changes.

**Comment by cdvv7788** [comment] 2020-10-07 15:34
@mauvity can you please check if the current version on master fixes it? We refactored the index internals.

**Comment by pirate** [comment] 2020-10-07 16:43
There is still a functional difference between the two ways:

- Delete button = delete the index record and all the archived files
- timestamp -> delete = delete only the index record without removing any archived files (they become orphans that will be re-imported on the next `archivebox init`)

**Comment by cdvv7788** [comment] 2020-10-07 17:01
Oh right, the delete functionality has not been touched in the refactor.

**Comment by cdvv7788** [comment] 2020-10-09 14:09
@pirate what should we do about this? Maybe add a confirmation and change both methods to remove the actual files? If the admin is a way to maintain the index, leaving orphaned folders may be unnecessary.

**Comment by pirate** [comment] 2020-10-10 01:54
I think removing the delete button from the snapshot admin detail page is enough for now. (Leave the delete button on the list page the way it is now).

**Comment by pirate** [comment] 2020-12-11 12:42
@cdvv7788 is this fixed in v0.5.0? If not can we do that.

**Comment by pirate** [comment] 2021-04-06 05:41
I'm pretty sure this was already fixed in v0.5.6. Comment back here if you're still seeing the issue and I'll reopen the ticket.

**Closed by pirate** 2021-04-06 05:41 UTC
Labels: is: bug, status: needs followup, status: wip

**Comment by pirate** [comment] 2024-01-04 22:26
@235 Can you confirm this is happening when you delete an older completed Snapshot that does not have the same URL present in a later import?

Deleting does not prevent a URL from being re-added in the future, so if you deleted some Snapshots and then re-imported the same URLs later on, they will re-appear (as *new* Snapshot entries).

Deleting *during* an import is also totally broken/not advised. This is the downside of making all my import code immutable/indempotent (it overwrites entries entirely on changes instead of mutating them in-place). Because Snapshots are operated on in-memory, it rewrites the DB and disk entries several times from memory as it does work during the import process, and as long as it's still in-memory being operated on it doesn't notice when a user deletes the DB/disk entry out from underneath it.

**Comment by 235** [comment] 2024-01-17 17:18
As discussed in the other ticket - this was deletion DURING an import. We can ignore the report here, and focus on on the other ticket discussion. TY!
