### ISSUE TITLE
Feature Request: browser addon

### ISSUE THREAD

**Issue by layderv** [ArchiveBox/ArchiveBox#689] opened 2021-04-01 12:39 UTC
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

I would like to click a button while browsing a webpage to add it to my archivebox without leaving my browser

## What hacks or alternative solutions have you tried to solve the problem?

Running `archivebox add url` in the terminal

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [ ] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

I've written a simple extension for Firefox to show what I'm looking for: https://github.com/layderv/archivefox
Extensions for other browsers and improvements to that one would be good.

**Comment by pirate** [comment] 2021-04-01 16:31
Duplicate of: https://github.com/ArchiveBox/ArchiveBox/issues/577

**Closed by pirate** 2021-04-01 16:31 UTC
Labels: status: idea phase
