### ISSUE TITLE
Feature Request: requests through proxy

### ISSUE THREAD

**Issue by wirehack7** [ArchiveBox/ArchiveBox#1317] opened 2024-01-11 21:00 UTC
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves

In some environments HTTP requests or even all outgoing requests have to go through a proxy. Or sometimes a proxy has to be used because of privacy reasons.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

ArchiveBox client may do requests for archiving through a proxy when settings are set in config (wget, curl, chrome, etc)

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment] 2024-01-11 22:11
Closing as duplicate of https://github.com/ArchiveBox/ArchiveBox/issues/249

**Closed by pirate** 2024-01-11 22:11 UTC
