### ISSUE TITLE
How to archive a url twice with different timestamp ? 

### ISSUE THREAD

**Issue by PKUFlyingPig** [ArchiveBox/ArchiveBox#692] opened 2021-04-06 01:58 UTC
I found that once a url has been archived, when I tried to add it to archivebox again it will fail. How can I archive one website twice but with different timestamp?

**Comment by pirate** [comment] 2021-04-06 02:30
Duplicate of: https://github.com/ArchiveBox/ArchiveBox/issues/179

**Closed by pirate** 2021-04-06 02:30 UTC
